--module Players.Edit exposing (..)
--
--import Html exposing (..)
--import Html.Attributes exposing (class, href, value)
--import Html.Events exposing (onClick, onInput)
--import Models exposing (Currency)
--import Msgs exposing (Msg)
--import Routing exposing (playersPath)
--
--
--view : Currency -> Html Msg
--view model =
--    div []
--        [ nav model
--        , input [ class "search-input", placeholder "Find coin", onInput Msgs.ChangeTest ] []
--        , form model
--        ]
--
--
--nav : Currency -> Html Msg
--nav model =
--    div [ class "clearfix mb2 white bg-black p1" ]
--        [ listBtn ]
--
--
--form : Currency -> Html Msg
--form player =
--    div [ class "m3" ]
--        [ h1 [] [ text player.name ]
--        , formLevel player
--        ]
--
--
--formLevel : Currency -> Html Msg
--formLevel player =
--    div
--        [ class "clearfix py1"
--        ]
--        [ div [ class "col col-5" ] [ text "Level" ]
--        , div [ class "col col-7" ]
--            [ btnLevelDecrease player
--            , btnLevelIncrease player
--            ]
--        ]
--
--
--btnLevelDecrease : Currency -> Html Msg
--btnLevelDecrease player =
--    let
--        message =
--            Msgs.ChangeLevel player -1
--    in
--    a
--        [ class "btn ml1 h1"
--        , onClick message
--        ]
--        [ i [ class "fa fa-minus-circle" ] [] ]
--
--
--btnLevelIncrease : Currency -> Html Msg
--btnLevelIncrease player =
--    let
--        message =
--            Msgs.ChangeLevel player 1
--    in
--    a [ class "btn ml1 h1", onClick message ]
--        [ i [ class "fa fa-plus-circle" ] [] ]
--
--
--listBtn : Html Msg
--listBtn =
--    a
--        [ class "btn regular"
--        , href playersPath
--        ]
--        [ i [ class "fa fa-chevron-left mr1" ] [], text "List" ]
